### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by fbizzarro** [xmarquez/democracyData#1]
Hi 

Thanks for creating this awesome package. As I try to download it, though, here is what happens:
```
`> https://github.com/xmarquez/democracyData.git
Error: unexpected '/' in "https:/"
> devtools::install_github("xmarquez/democracyData")
Downloading GitHub repo xmarquez/democracyData@master
from URL https://api.github.com/repos/xmarquez/democracyData/zipball/master
Installing democracyData
"C:/PROGRA~1/R/R-33~1.2/bin/i386/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/fbizz/AppData/Local/Temp/RtmpoJkGSb/devtools4a903768380b/xmarquez-democracyData-b0f58ce"  \
  --library="C:/Users/fbizz/Documents/R/win-library/3.3" --install-tests 

ERROR: dependency 'fuzzyjoin' is not available for package 'democracyData'
* removing 'C:/Users/fbizz/Documents/R/win-library/3.3/democracyData'
Error: Command failed (1)`
```

Would you mind taking a look? 
Thanks
F

**Comment by xmarquez** [comment]
Hi fbizarro - I'll take a look later today, but have you tried `install.packages("fuzzyjoin")` before doing `devtools::install_github("xmarquez/democracyData")`?

**Comment by xmarquez** [comment]
The [`fuzzyjoin`](https://cran.r-project.org/web/packages/fuzzyjoin/index.html) package should be available for R 3.3.

**Comment by fbizzarro** [comment]
Of course, thanks!

**Comment by xmarquez** [comment]
fbizarro - unfortunately I cannot replicate the issue. When I uninstall the package from my machine, uninstall the dependencies, and run `devtools::install_github("xmarquez/democracyData")`, it works fine - downloads all the dependencies and installs everything. Maybe you have an option set in devtools that does not allow you to automatically download all dependencies?
