### ISSUE TITLE
Documentation: Usage in Python?

### ISSUE THREAD

**Issue by BrandonKMLee** [xmarquez/democracyData#10]
This dataset looks useful, are there ways to have this work in Python instead of R? https://github.com/xmarquez/democracyData#installation

**Comment by xmarquez** [comment]
At the moment I'm not planning to do this, sorry!

**Comment by BrandonKMLee** [comment]
Apologies but can Rda be converted to CSV or some other format?
https://github.com/xmarquez/democracyData/tree/master/data

**Comment by JoeNoonan** [comment]
Yes. Just load it into R then export it as a CSV using write.csv().

**Comment by BrandonKMLee** [comment]
Can Python read Rda files?

**Comment by xmarquez** [comment]
Yes, you will need the rpy2 package. See
https://stackoverflow.com/questions/47833692/converting-rda-to-pandas-dataframe
