### ISSUE TITLE
Changes in download URL for Bertelsmann Transformation Index data

### ISSUE THREAD

**Issue by alxhntl** [xmarquez/democracyData#11]
Hi Xavier,

using the "generate_democracy_scores_dataset" function the given URL can´t be opened.
It seems as the BTI project changed the URL for data download.

Best Regards,

Alex

**Comment by xmarquez** [comment]
Thanks Alex for alerting me to this.

Are you using generate_democracy_scores_dataset with force_redownload =
TRUE? You should be able to use the archived version of BTI (type bti, or
use generate_democracy_scores_dataset with the default  force_redownload =
FALSE) while I fix the problem. I do see the link for downloading has
changed.

Xavier

**Comment by xmarquez** [comment]
Hi Alexander - I've updated the package (including the BTI dataset) and
this issue should be resolved now if you update the package. Thanks!
