### ISSUE TITLE
Freedom House score for 1981

### ISSUE THREAD

**Issue by anthlittle** [xmarquez/democracyData#12]
The data from from download_fh does not include data for 1981. From looking at the raw spreadsheet I'm guessing this is due to the change in what time periods are covered by each annual report: in particular the "1982" report covers almost two years (Jan.1981-Aug. 1982). Would it make sense to use the scores from this report for both 1981 and 1982?

Thanks!

**Comment by xmarquez** [comment]
Yes, this is right - it's explained in the documentation for download_fh: "The surveys cover specific periods in the original data that do not always overlap with a single year. In particular, the year 1981 is "skipped" -- a single survey covers Jan. 1981 - Aug. 1982 and its value is assigned to 1982 here. Surveys from 1981 to 1988 covered the periods Jan. 1981-Aug. 1982, Aug. 1982-Nov. 1983, Nov. 1983-Nov. 1984, Nov. 1984-Nov. 1985, Nov. 1985-Nov. 1986, Nov. 1986-Nov. 1987, Nov. 1987-Nov. 1988, and Nov.1988-Dec.1989, and results are assigned to years 1982, 1983, 1984, 1985, 1986, 1987, 1988, and 1989."

**Comment by xmarquez** [comment]
See also: https://xmarquez.github.io/democracyData/reference/download_fh.html

**Comment by xmarquez** [comment]
(Same as #5)
