### ISSUE TITLE
Loading FH Dataset after download

### ISSUE THREAD

**Issue by THGratzi** [xmarquez/democracyData#13]
Hi Xavier, 

I'm terribly sorry to ask this but I'm quite new to downloading datasets through Github on RStudio. I've been able to get the download_fh function to run but don't know how to load the processed dataset or where I can find its download location. Wondering if you'd be able to provide some quick insight. Thanks.

**Comment by xmarquez** [comment]
Hi THGratzy, normally you'd do this:

```
remotes::install_github("xmarquez/democracyData")
library(democracyData)
fh <- download_fh()
fh
```
And fh will be your Freedom House dataset. Have you tried this?

**Comment by THGratzi** [comment]
Ah, it looks like I missed the specific part of the command to save the downloaded file to "fh". I went off the website commands instead of using your readme which is entirely my fault. Many thanks.
