### ISSUE TITLE
redownload_svmdi

### ISSUE THREAD

**Issue by jakubpolan** [xmarquez/democracyData#3]
The link for the 2018 svmdi release is no longer valid. You can access it now as an xlsx file [here](https://uca8d06c8babea088052df582c26.dl.dropboxusercontent.com/cd/0/get/AksqkhFGJlrDQkFgufM7riIUdMDLBvoWeQautvzsL-snZFFxNsFCWw_6DXX9vjQ2OL3xz784rXU9YIgdns3zGEEw6njABiSYDIyIKmvH7ddAyg/file?_download_id=7840151322346982227691344607073480318115496641825082676675925409&_notify_domain=www.dropbox.com&dl=1). The 2016 release is still accessible as an xlsx file [here](https://www.wiwi.uni-wuerzburg.de/fileadmin/12010400/Data.xlsx).

**Comment by xmarquez** [comment]
Hi jakubpolan - the new link gives me a 403 error. Is there a webpage that
hosts the data?

**Comment by jakubpolan** [comment]
Hi, sorry for the broken link - I tried it a few times before posting and it seemed to work. The data is on the author's personal [Dropbox](https://www.dropbox.com/s/a7yqs5txt3qpwn0/Index%20Upload.xlsx?dl=0) which I was directed to from his [website](http://tommykrieger.eu/).

**Comment by xmarquez** [comment]
Thanks - I can get it now. I'll fix the download link and push the changes
later this week.

**Comment by xmarquez** [comment]
I've pushed the changes - it should be working now.
