### ISSUE TITLE
no Freedom House data for 1981

### ISSUE THREAD

**Issue by mayeulk** [xmarquez/democracyData#5]
There is no data with year == 1981 in the Freedom House dataset
```
fh <- download_fh(verbose = FALSE)
table(fh$year)
1972 1973 1974 1975 1976 1977 1978 1979 1980 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 
 149  150  152  158  158  154  157  160  161  163  164  165  165  165  165  165  166  164  182  186  190  191  191  191  191  191  192  192  192  192  192  192  192  193  193  193  194  194  195  195  195 
2014 2015 2016 2017 2018 
 195  195  195  195  195
```
I have not checked the URL in the source code. However from https://freedomhouse.org/content/freedom-world-data-and-resources the first Excel file at https://freedomhouse.org/sites/default/files/Country%20and%20Territory%20Ratings%20and%20Statuses%20FIW1973-2018.xlsx has some data for 1981.

**Comment by xmarquez** [comment]
Hi Mayeul,

This has to do with the treatment of 1981-1982 in Freedom House's survey.
Most political science research codes the 1981-1982 survey year as 1982,
even though it covered 1981 and part of 1982. So one year is missing -
either 1981 or 1982 has to disappear.

Best,

Xavier

**Comment by xmarquez** [comment]
More specifically:

The FH data has the following:

1981 1982
1980 Jan.1981-Aug. 1982
So the "1981" release covers the year 1980, so it appears as 1980 in this
data (in keeping with political science conventions); the 1982 release
covers 1981-August 1982, so it appears as 1982 in this data.
