### ISSUE TITLE
Having issues downloading the metadat

### ISSUE THREAD

**Issue by hamid004** [xmarquez/democracyData#6]
I tried to download the metadata using the command generate_democracy_scores_dataset (output format=wide, verbose=F)
 It started well until it reached a point where it encountered an error.. 
Error in utils:: download.file(path,tmpfile,quite=!verbose):
Cannot open URL 'http://databank.worldbank.org/data/download/WGI_CSV.zip"
.. What could be the cause of this and what is the possible solution..

Thanks

**Comment by xmarquez** [comment]
Hi hamid004 - it works fine for me. Sometimes the websites are down - it
could just be a matter of trying again. You could also just try
using download_wgi_voice_and_accountability() to see if it's just the WB's
voice and accountability index that is not responding.

**Comment by hamid004** [comment]
Thanks for the response. I tried download_wgi_voice_and_accountability() and I got the same error message

**Comment by hamid004** [comment]
When I later tried downloading again. Here's the error I got 
![nw_democrat](https://user-images.githubusercontent.com/68087047/128579619-c511b5d5-51b6-4d55-a55a-a94d4b16b909.png)

**Comment by xmarquez** [comment]
Hi hamid004 - it still works for me. Maybe your version of dplyr is not the
latest? In the last update to the package, I refactored the code so it
would work with the latest version of dplyr. Could you run sessionInfo() to
see what you get? Another possibility may be that there is some problem
with the WB website from which that dataset comes - maybe a proxy
connection problem?

**Comment by hamid004** [comment]
Thanks a lot.. I later found that my windows firewall is blocking the connection and also update the dplyr and everything worked.. Thanks
